### Datasets

In [1]:
import pandas as pd

In [2]:
inflow = pd.read_parquet('/uss/hdsi-prismdata/q1-ucsd-inflows.pqt')
outflow = pd.read_parquet('/uss/hdsi-prismdata/q1-ucsd-outflows.pqt')

In [3]:
inflow.sample(5)

,prism_consumer_id,prism_account_id,memo,amount,posted_date,category
13249,145,acc_414,PAYCHECK,589.31,2022-06-16,PAYCHECK
373085,4312,acc_7895,DEPOSIT,160.00,2022-02-14,DEPOSIT
422400,4872,acc_8455,EXTERNAL_TRANSFER,83.00,2022-12-06,EXTERNAL_TRANSFER
439424,5071,acc_8654,REFUND,38.09,2021-09-27,REFUND
101727,1092,acc_3094,PAYCHECK_PLACEHOLDER,576.12,2020-05-01,PAYCHECK_PLACEHOLDER

In [4]:
outflow.sample(5)

,prism_consumer_id,prism_account_id,memo,amount,posted_date,category
318214,691,acc_2000,UNCATEGORIZED,50.00,2022-07-15,UNCATEGORIZED
2216041,5222,acc_8805,229 DBT CRD XXXX 11/12/21 XXXXXXXXeBay O*04-XX...,28.09,2021-11-15,GENERAL_MERCHANDISE
1797127,4442,acc_8025,EXTERNAL_TRANSFER,2.00,2020-12-29,EXTERNAL_TRANSFER
2167839,5124,acc_8707,SAMSCLUB #XXXX CINNAMINSON NJ 1...,30.00,2022-11-04,GENERAL_MERCHANDISE
1860343,4552,acc_8135,ACCOUNT_FEES,0.73,2022-06-21,ACCOUNT_FEES

# What are the most common merchants per category? [pick 5-10 categories]

### Looking at the dataframes above, it seems that merchant data is stored in the memo column. But before digging into the merchants, we will browse through the categories.

In [5]:
inflow['category'].value_counts()

category
EXTERNAL_TRANSFER        156533
SELF_TRANSFER            110437
DEPOSIT                   61345
MISCELLANEOUS             55648
PAYCHECK                  33138
PAYCHECK_PLACEHOLDER      26087
REFUND                    23220
INVESTMENT_INCOME         17325
SMALL_DOLLAR_ADVANCE      13621
OTHER_BENEFITS             7708
TAX                        3405
LOAN                       2513
UNEMPLOYMENT_BENEFITS      1961
INSURANCE                   174
Name: count, dtype: int64

In [6]:
outflow['category'].value_counts()

category
GENERAL_MERCHANDISE    524063
FOOD_AND_BEVERAGES     481994
EXTERNAL_TRANSFER      320998
GROCERIES              219331
AUTOMOTIVE             208579
ATM_CASH               117651
UNCATEGORIZED          117409
LOAN                    90945
ENTERTAINMENT           80885
ESSENTIAL_SERVICES      77137
CREDIT_CARD_PAYMENT     75506
SELF_TRANSFER           73281
TRAVEL                  59647
HEALTHCARE_MEDICAL      40842
ACCOUNT_FEES            37511
INSURANCE               30244
PETS                     9266
HOME_IMPROVEMENT         8600
GIFTS_DONATIONS          4719
EDUCATION                4499
OVERDRAFT                3386
TAX                      3186
RENT                     3147
BNPL                     1543
MORTGAGE                 1119
PAYCHECK                 1040
CHILD_DEPENDENTS          936
BILLS_UTILITIES            23
AUTO_LOAN                   1
Name: count, dtype: int64

### Let's look through each category and see what merchants there are.

In [7]:
inflow[inflow['category'] == 'EXTERNAL_TRANSFER']['memo'].value_counts()

memo
EXTERNAL_TRANSFER    156533
Name: count, dtype: int64

In [8]:
inflow[inflow['category'] == 'SELF_TRANSFER']['memo'].value_counts()

memo
SELF_TRANSFER    110437
Name: count, dtype: int64

In [9]:
inflow['memo'].value_counts()

memo
EXTERNAL_TRANSFER        156533
SELF_TRANSFER            110437
DEPOSIT                   61345
MISCELLANEOUS             55648
PAYCHECK                  33138
PAYCHECK_PLACEHOLDER      26087
REFUND                    23220
INVESTMENT_INCOME         17325
SMALL_DOLLAR_ADVANCE      13621
OTHER_BENEFITS             7708
TAX                        3405
LOAN                       2513
UNEMPLOYMENT_BENEFITS      1961
INSURANCE                   174
Name: count, dtype: int64

### It seems that there are no merchant information in the inflow df.

In [10]:
outflow['memo'].value_counts()

memo
EXTERNAL_TRANSFER                                                                    320998
AUTOMOTIVE                                                                           208579
ATM_CASH                                                                             117651
UNCATEGORIZED                                                                        117409
LOAN                                                                                  90945
                                                                                      ...
Par Gators Dockside -                                                                     1
Chilis Mandarin                                                                           1
Chilis Bay Meadows                                                                        1
Southside Liquor                                                                          1
POS WITHDRAWALWAL-MART #XXXX XXXX E MCKELLIPS RD MESA AZ  Card 15 #XXXX  MCC XXXX         1
Name: count, Length: 528786, dtype: int64

### There are in outflow so let's explore more.

In [11]:
outflow[outflow['category'] == 'GENERAL_MERCHANDISE']['memo'].value_counts()

memo
Amazon                                                                                                                           31725
7-Eleven                                                                                                                         11675
Circle K                                                                                                                         10148
Dollar General                                                                                                                    7872
Apple                                                                                                                             7394
                                                                                                                                 ...
PURCHASE 06-17 FLEXSHOPPER , FL VNT XXXX                                                                                             1
PURCHASE 08-10 PLAYSTATIO FOSTER CITY, CA STR XXXX                                                                                   1
PURCHASE 09-21 FLEXSHOPPER ECOMMERCE , FL VNT XXXX                                                                                   1
PURCHASE 09-03 HELP.HBOMAX.COM HTTPSHBOMAX.C, NY VNT XXXX                                                                            1
DEBIT CARD WITHDRAWAL PURCHASEAmazon Prime*TI40L27R3 Amzn.com/bill WA Date 01/16/23 PURCH XXXXXXXXXXXXXXXXXXXXXX  Card 15 #34        1
Name: count, Length: 217779, dtype: int64

In [12]:
outflow[outflow['category'] == 'CHILD_DEPENDENTS']['memo'].value_counts()

memo
CHILD_DEPENDENTS    936
Name: count, dtype: int64

### Some categories had a large variety of merchants while others had none/few as seen above. We continued looking at each category and chose the following ones to work with because they have a wider range of merchant variety.

In [13]:
chosen_cats = ['GENERAL_MERCHANDISE', 'FOOD_AND_BEVERAGES', 'GROCERIES', 'TRAVEL', 'PETS', 'RENT']

In [21]:
cat_df = outflow[outflow['category'].isin(chosen_cats)]
df = cat_df.groupby(['category', 'memo']).count()
# .sort_values(by='prism_account_id', ascending=False)
# .reset_index().set_index('category')
df

                                                                       prism_consumer_id  \
category           memo
FOOD_AND_BEVERAGES # (800) 544-XXXX 139 EAST FOURTH STREET CINCINN...                  6
                   # 101                                                               1
                   # 102                                                               1
                   # 103                                                               1
                   # 104                                                               1
...                                                                                  ...
TRAVEL             debit card JACK LONDON INN OAKLAND CA Date 08/2...                  1
                   debit card PASADENA PARKIN 33 E GREEN ST PASADE...                  1
                   dox*Bay Area FasTrak doxo.io/help WA         10/11                  1
                   eDreams BARCELONA 01/21                                             1
                   www.cvs.com XXXX ENTERPRISE DR REC 800-746                          1

                                                                       prism_account_id  \
category           memo
FOOD_AND_BEVERAGES # (800) 544-XXXX 139 EAST FOURTH STREET CINCINN...                 6
                   # 101                                                              1
                   # 102                                                              1
                   # 103                                                              1
                   # 104                                                              1
...                                                                                 ...
TRAVEL             debit card JACK LONDON INN OAKLAND CA Date 08/2...                 1
                   debit card PASADENA PARKIN 33 E GREEN ST PASADE...                 1
                   dox*Bay Area FasTrak doxo.io/help WA         10/11                 1
                   eDreams BARCELONA 01/21                                            1
                   www.cvs.com XXXX ENTERPRISE DR REC 800-746                         1

                                                                       amount  \
category           memo
FOOD_AND_BEVERAGES # (800) 544-XXXX 139 EAST FOURTH STREET CINCINN...       6
                   # 101                                                    1
                   # 102                                                    1
                   # 103                                                    1
                   # 104                                                    1
...                                                                       ...
TRAVEL             debit card JACK LONDON INN OAKLAND CA Date 08/2...       1
                   debit card PASADENA PARKIN 33 E GREEN ST PASADE...       1
                   dox*Bay Area FasTrak doxo.io/help WA         10/11       1
                   eDreams BARCELONA 01/21                                  1
                   www.cvs.com XXXX ENTERPRISE DR REC 800-746               1

                                                                       posted_date
category           memo
FOOD_AND_BEVERAGES # (800) 544-XXXX 139 EAST FOURTH STREET CINCINN...            6
                   # 101                                                         1
                   # 102                                                         1
                   # 103                                                         1
                   # 104                                                         1
...                                                                            ...
TRAVEL             debit card JACK LONDON INN OAKLAND CA Date 08/2...            1
                   debit card PASADENA PARKIN 33 E GREEN ST PASADE...            1
                   dox*Bay Area FasTrak doxo.io/help WA         10/11            1
                   eDreams BARCELONA 01/21                                       1
                   www.cvs.com XXXX ENTERPRISE DR REC 800-746                    1

[525627 rows x 4 columns]

In [37]:
outflow[outflow['category']=='FOOD_AND_BEVERAGES']['memo'].value_counts()[:10]

memo
McDonald's                22670
Starbucks                 12777
Chick-fil-A                7933
Taco Bell                  6071
Wendy's                    4694
Burger King                4282
Dunkin' Donuts             4265
McDonald''s                3875
Sonic                      2925
Chipotle Mexican Grill     2679
Name: count, dtype: int64

In [33]:
gm = df.loc['GENERAL_MERCHANDISE'][['prism_consumer_id']].sort_values(by='prism_consumer_id', ascending = False)

In [36]:
gm[:50]

                                                    prism_consumer_id
memo
Amazon                                                          31725
7-Eleven                                                        11675
Circle K                                                        10148
Dollar General                                                   7872
Apple                                                            7394
Home Depot                                                       7213
Costco                                                           4760
Google                                                           4567
APPLE.COM/BILL                                                   3270
Amazon Prime                                                     3159
Family Dollar                                                    2983
Lowe's                                                           2425
Afterpay                                                         2199
Best Buy                                                         2188
Dollar Tree                                                      1984
CHECKCARD XXXX APPLE.COM/BILL CA XXXXXXXXXXXXXX...               1503
Apple Cash                                                       1428
Sam's Club                                                       1324
PURCHASE XXXX APPLE.COM/BILL XXX-XXX-XXXX CA XX...               1225
Audible                                                          1138
Kohl's                                                           1138
PURCHASE XXXX APPLE.COM/BILL CA XXXXXXXXXXXXXXX...                953
Lowe''s                                                           920
Nordstrom                                                         904
PURCHASE XXXX APPLE.COM/BILL CA XXXXXXXXXXXXXXX...                881
Old Navy                                                          817
Goodwill                                                          786
CHECKCARD XXXX APPLE.COM/BILL XXX-XXX-XXXX CA X...                782
Amazon Music                                                      742
Microsoft                                                         728
JCPenney                                                          695
APPLE CASH 1INFINITELOOP                                          677
CHECKCARD XXXX APPLE.COM/BILL CA XXXXXXXXXXXXXX...                616
AFTERPAY                                                          582
BETRIVERS.COM                                                     577
AMAZON.COM                                                        573
Sony Playstation                                                  565
Five Below                                                        559
CASH APP*KALI D XXXXXXXXXX /CA US CARD PURCHASE                   554
Electronic Withdrawal Kwik Trip Inc                               536
Playstation                                                       532
Great Clips                                                       516
Cumberland Farms                                                  512
PURCHASE XXXX APPLE.COM/BILL XXX-XXX-XXXX CA XX...                508
FedEx                                                             500
Central Cents Withdrawal Transferred to Acct#: ...                497
POS Debit - Visa Check Card XXXX - APPLE.COM BI...                491
CHECKCARD XXXX CRYPTO.COM XXX-XXXXXXX DE XXXXXX...                478
PAYPAL           INST XFER  APPLE.COM BILL  WEB...                477
Debit Withdrawal BETRIVERS.COM XXXXXX                             457